<?php

namespace ContainerHePDJu5;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getApiPlatform_PaginationOptionsService extends App_KernelTestDebugContainer
{
    /**
     * Gets the private 'api_platform.pagination_options' shared service.
     *
     * @return \ApiPlatform\Core\DataProvider\PaginationOptions
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/api-platform/core/src/DataProvider/PaginationOptions.php';

        return $container->privates['api_platform.pagination_options'] = new \ApiPlatform\Core\DataProvider\PaginationOptions(true, 'page', false, 'itemsPerPage', false, 'pagination');
    }
}
