<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHePDJu5\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHePDJu5/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerHePDJu5.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerHePDJu5\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerHePDJu5\App_KernelTestDebugContainer([
    'container.build_hash' => 'HePDJu5',
    'container.build_id' => '5f1e12ea',
    'container.build_time' => 1624707369,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHePDJu5');
