<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerFduiax7\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerFduiax7/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerFduiax7.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerFduiax7\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerFduiax7\App_KernelTestDebugContainer([
    'container.build_hash' => 'Fduiax7',
    'container.build_id' => '70f26ee3',
    'container.build_time' => 1624704241,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerFduiax7');
