<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerSEglXHD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerSEglXHD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerSEglXHD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerSEglXHD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerSEglXHD\App_KernelDevDebugContainer([
    'container.build_hash' => 'SEglXHD',
    'container.build_id' => '13a62239',
    'container.build_time' => 1624886355,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerSEglXHD');
