<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXZUUeIc\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXZUUeIc/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXZUUeIc.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXZUUeIc\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXZUUeIc\App_KernelDevDebugContainer([
    'container.build_hash' => 'XZUUeIc',
    'container.build_id' => 'ef5400e8',
    'container.build_time' => 1624785344,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXZUUeIc');
