<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerYrhjbIN\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerYrhjbIN/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerYrhjbIN.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerYrhjbIN\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerYrhjbIN\App_KernelDevDebugContainer([
    'container.build_hash' => 'YrhjbIN',
    'container.build_id' => 'fc0ffd77',
    'container.build_time' => 1624796647,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerYrhjbIN');
